package com.basiclab.iot.sink.polling;

/** Stable, closed error vocabulary written to collector observed.json. */
public enum CollectorConfigErrorCode {
    COLLECTOR_CONFIG_NOT_AVAILABLE,
    COLLECTOR_CONFIG_TOO_LARGE,
    COLLECTOR_CONFIG_JSON_INVALID,
    COLLECTOR_CONFIG_SCHEMA_INVALID,
    COLLECTOR_CONFIG_CANONICAL_INVALID,
    COLLECTOR_CONFIG_WORKLOAD_MISMATCH,
    COLLECTOR_CONFIG_VERSION_STALE,
    COLLECTOR_CONFIG_VERSION_CONFLICT,
    COLLECTOR_CONFIG_STATE_CORRUPT,
    COLLECTOR_CONFIG_PERMISSION_INVALID,
    COLLECTOR_CONFIG_WRITE_FAILED,
    COLLECTOR_CONFIG_APPLY_FAILED
}
